import React from './globals.css'
import Header from '../components/header'
import Footer from '../components/footer'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout() {
  return (
    <html lang="en">
       <head>
          <link href="https://fonts.googleapis.com/css2?family=Rajdhani:wght@300&display=swap" rel="stylesheet" />
        </head>
      <body>
        <Header />
        <div className='mt-20 w-full mb-24'>
          <div className='w-3/5 text-left mx-auto mb-16 font-["Rajdhani"] text-5xl text-[#4F4CEE] font-bold'>
            <h2>Sign Up |</h2>
          </div>
          <div className='w-3/6 text-center mx-auto mb-10 leading-10'>
            <form method='' action='/' className='text-center relative font-["Rajdhani"] '>
              <div className='flex justify-evenly px-20'>
                <div className='mr-10'>
                  <div className='flex flex-col text-center mb-10'>
                    <p className='p-0 px-2 text-left absolute top-[-35px] left-[50px] rounded text-[#000] font-bold text-md'>First Name</p>
                    <input className='py-1 px-3 w-80 border-2 border-[#00000060] rounded-lg font-bold text-xl' type="text" name='name' placeholder='Name' />
                  </div>
                  <div className='flex flex-col text-center mb-10'>
                    <p className='p-0 px-2 text-left absolute top-[48px] left-[50] rounded text-[#000] font-bold text-md'>Last Name</p>
                    <input className='py-1 px-3 w-80 border-2 border-[#00000060] rounded-lg font-bold text-xl' type="text" name='last name' placeholder='Last Name' />
                  </div>
                  <div className='flex flex-col text-center'>
                    <p className='p-0 px-2 text-left absolute top-[130px] left-[50px] rounded text-[#000] font-bold text-md'>Email</p>
                    <input className='py-1 px-3 w-80 border-2 border-[#00000060] rounded-lg font-bold text-xl' type="email" name='email' placeholder='Email Adress' />
                  </div>
                </div>
                <div>
                  <div className='flex flex-col text-center mb-10'>
                    <p className='p-0 px-2 text-left absolute top-[-35px] left-[410px] rounded text-[#000] font-bold text-md'>Phone Number</p>
                    <input className='py-1 px-3 w-80 border-2 border-[#00000060] rounded-lg font-bold text-xl' type="text" name='number' placeholder='Phone Number' />
                  </div>
                  <div className='flex flex-col text-center mb-10'>
                    <p className='p-0 px-2 text-left absolute top-[48px] left-[410px] rounded text-[#000] font-bold text-md'>Password</p>
                    <input className='py-1 px-3 w-80 border-2 border-[#00000060] rounded-lg font-bold text-xl' type="password" name='password' placeholder='Password' id='password' />
                    <button id='show' className='absolute right-16'>Show</button>
                  </div>
                  <div className='flex flex-col text-center mb-10'>
                    <p className='p-0 px-2 text-left absolute top-[130px] left-[410px] rounded text-[#000] font-bold text-md'>Password Repeat</p>
                    <input className='py-1 px-3 w-80 border-2 border-[#00000060] rounded-lg font-bold text-xl' type="password" name='password-r' placeholder='Password' id='password-r' />
                    <button id='show' className='absolute right-16'>Show</button>
                  </div>
                </div>
              </div>

                <div className='text-left ml-14'>
                    <input type="checkbox" id="myCheckbox" name="myCheckbox"  className='mr-2 ' />
                    <label htmlFor="myCheckbox" className='font-bold'>Kişisel verilerimin işlenmesine yönelik <span className=' border-b-2 border-[#0000005b]'>aydınlatma metnini</span> okudum ve kabul ediyorum</label>
                </div>
                <div className='text-left ml-14'>
                    <input type="checkbox" id="myCheckbox" name="myCheckbox"  className='mr-2' />
                    <label htmlFor="myCheckbox" className='font-bold leading-3'>Kampanyalardan haberdar olabilmem için kişisel verilerimin işlenmesini ve tarafıma elektronik ileti gönderilmesini kabul ediyorum.</label>
                </div>
              <button className='text-4xl font-bold py-2 px-10 text-white rounded-md bg-[#4F4CEE] mt-6' >Sign Up</button>
            </form>
          </div>
        </div>
              
                





        <Footer />
      </body>
    </html>
  )
}
