import '@/styles/reset.css'
import '@/styles/globals.css'

import { Header, Footer } from '@/components'
import { Inter } from 'next/font/google'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const inter = Inter({ subsets: ['latin'] })


export default function RootLayout({ children }) {

  return (
    <html lang="en" className={inter.className}>
      <head />
      <body>
        <Header scrolled />
        {children}
        <Footer />
      </body>
    </html>
  )
}
