import React from './globals.css'
import Header from '../components/header'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout() {
  return (
    <html lang="en">
       <head>
          <link href="https://fonts.googleapis.com/css2?family=Rajdhani:wght@300&display=swap" rel="stylesheet" />
        </head>
      <body>
        <Header />
      </body>
    </html>
  )
}
